name: Update ALG Data

on:
  schedule:
    # Ejecutar todos los lunes a las 9:00 AM (UTC)
    - cron: '0 9 * * 1'
  workflow_dispatch: # Permite ejecución manual

jobs:
  update-alg:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Update ALG data
      run: python scripts/update_alg_data.py
    
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data/
        if ! git diff --staged --quiet; then
          git commit -m "Update ALG data - $(date '+%Y-%m-%d')"
          git push
        else
          echo "No changes to commit"
        fi